package carestack.encounter.documentLinking.dto;

import com.fasterxml.jackson.annotation.JsonAlias;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import carestack.base.enums.DocLinkingEnums;

import java.util.List;

/**
 * Represents the response received after successfully creating a care context.
 * <p>
 * This DTO contains the essential identifiers generated by the API, such as the
 * care context reference and request ID, which are required for later steps
 * in the document linking a process.
 * </p>
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class CreateCareContextResponse {

    /**
     * The unique reference identifier for the newly created care context.
     */
    @JsonAlias("careContextReference")
    private String careContextReference;

    /**
     * The unique identifier for the entire transaction request.
     */
    @JsonAlias("requestId")
    private String requestId;

    /**
     * A list of authentication modes supported or required for this care context.
     */
    @JsonAlias("authModes")
    private List<DocLinkingEnums.AuthMode> authModes;
}